// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvVQsyuc-z42fxW9VdD2ud3ZMhKoHSUSA',
    appId: '1:288704412759:web:c281f0e5c3b08c371cf712',
    messagingSenderId: '288704412759',
    projectId: 'devpoint-solutions',
    authDomain: 'devpoint-solutions.firebaseapp.com',
    storageBucket: 'devpoint-solutions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-AA2KsAmazkcH3s1GPjTQv1m9UqIX3jo',
    appId: '1:288704412759:android:369523a99354164d1cf712',
    messagingSenderId: '288704412759',
    projectId: 'devpoint-solutions',
    storageBucket: 'devpoint-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNO2P75ITBBa3Z_-p9sUBcSb-TZga4RQ',
    appId: '1:288704412759:ios:1376c1bc70df1e941cf712',
    messagingSenderId: '288704412759',
    projectId: 'devpoint-solutions',
    storageBucket: 'devpoint-solutions.appspot.com',
    iosBundleId: 'com.example.devpointSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPNO2P75ITBBa3Z_-p9sUBcSb-TZga4RQ',
    appId: '1:288704412759:ios:1376c1bc70df1e941cf712',
    messagingSenderId: '288704412759',
    projectId: 'devpoint-solutions',
    storageBucket: 'devpoint-solutions.appspot.com',
    iosBundleId: 'com.example.devpointSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvVQsyuc-z42fxW9VdD2ud3ZMhKoHSUSA',
    appId: '1:288704412759:web:9d40e232bbab097e1cf712',
    messagingSenderId: '288704412759',
    projectId: 'devpoint-solutions',
    authDomain: 'devpoint-solutions.firebaseapp.com',
    storageBucket: 'devpoint-solutions.appspot.com',
  );
}
